-- SCE066 customer email workflow
-- Run manually on DB2 AS400 after backup/review.
-- Prerequisite: ITPROD.SHCUMAILD.RECIPIENT_TYPE must be CHAR(10) or wider so it can store NOTICE.

ALTER TABLE ITPROD.SHDOCH ADD COLUMN SHMLST CHAR(1) NOT NULL DEFAULT '';
ALTER TABLE ITPROD.SHDOCH ADD COLUMN SHMLTS TIMESTAMP;
ALTER TABLE ITPROD.SHDOCH ADD COLUMN SHMLUS CHAR(20) NOT NULL DEFAULT '';
ALTER TABLE ITPROD.SHDOCH ADD COLUMN SHMLCT INTEGER NOT NULL DEFAULT 0;

CREATE TABLE ITPROD.SHCUEMAILL (
    LOG_ID          INTEGER GENERATED ALWAYS AS IDENTITY,
    MAIL_KIND       VARCHAR(20)    NOT NULL,
    INVOICE_NO      CHAR(20)       NOT NULL,
    CUSTOMER_CODE   CHAR(10)       NOT NULL,
    TO_RECIPIENTS   VARCHAR(2000)  NOT NULL DEFAULT '',
    CC_RECIPIENTS   VARCHAR(2000)  NOT NULL DEFAULT '',
    SUBJECT_TEXT    VARCHAR(500)   NOT NULL DEFAULT '',
    BODY_TEXT       CLOB(64K),
    STATUS          VARCHAR(20)    NOT NULL,
    ERROR_MSG       VARCHAR(2000)  NOT NULL DEFAULT '',
    SENT_USER       CHAR(20)       NOT NULL DEFAULT '',
    SENT_TIMESTAMP  TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT PK_SHCUEMAILL PRIMARY KEY (LOG_ID)
);

CREATE TABLE ITPROD.SHCUMAILT (
    TEMPLATE_CODE     VARCHAR(50)   NOT NULL,
    SUBJECT_TEMPLATE  VARCHAR(250)  NOT NULL,
    BODY_TEMPLATE     CLOB(64K)     NOT NULL,
    ACTIVE_STATUS     CHAR(1)       NOT NULL DEFAULT 'Y',
    CREATED_DATE      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE      TIMESTAMP,
    UPDATED_USER      CHAR(20)      NOT NULL DEFAULT '',

    CONSTRAINT PK_SHCUMAILT PRIMARY KEY (TEMPLATE_CODE),
    CONSTRAINT CK_SHCUMAILT_STATUS CHECK (ACTIVE_STATUS IN ('Y', 'N'))
);

CREATE TABLE ITPROD.SHCUMAILS (
    SENDER_CODE     VARCHAR(30)   NOT NULL,
    SENDER_EMAIL    VARCHAR(150)  NOT NULL,
    APP_PASSWORD    VARCHAR(300)  NOT NULL,
    ACTIVE_STATUS   CHAR(1)       NOT NULL DEFAULT 'Y',
    CREATED_DATE    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE    TIMESTAMP,
    UPDATED_USER    CHAR(20)      NOT NULL DEFAULT '',

    CONSTRAINT PK_SHCUMAILS PRIMARY KEY (SENDER_CODE),
    CONSTRAINT CK_SHCUMAILS_STATUS CHECK (ACTIVE_STATUS IN ('Y', 'N'))
);

INSERT INTO ITPROD.SHCUMAILT
    (TEMPLATE_CODE, SUBJECT_TEMPLATE, BODY_TEMPLATE, ACTIVE_STATUS, CREATED_DATE, UPDATED_DATE, UPDATED_USER)
VALUES
    (
        'CUSTOMER_INVOICE',
        'Invoice {INVOICE_NO} - {CUSTOMER_NAME}',
        '<p>Dear Customer,</p><p>Please find invoice document for {INVOICE_NO}.</p><p>Customer: {CUSTOMER_CODE} {CUSTOMER_NAME}</p>',
        'Y',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP,
        ''
    );

INSERT INTO ITPROD.SHCUMAILS
    (SENDER_CODE, SENDER_EMAIL, APP_PASSWORD, ACTIVE_STATUS, CREATED_DATE, UPDATED_DATE, UPDATED_USER)
VALUES
    (
        'CUSTOMER_INVOICE',
        'siripong.j@patayafood.com',
        '',
        'Y',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP,
        'SYSTEM'
    );

-- Add NOTICE recipients manually in SHCUMAILD, for example:
-- INSERT INTO ITPROD.SHCUMAILD
--     (CUSTOMER_CODE, RECIPIENT_TYPE, EMAIL_SEQ, EMAIL_ADDRESS, ACTIVE_STATUS, CREATED_DATE)
-- VALUES
--     ('ALL', 'NOTICE', 1, 'team@example.com', 'Y', CURRENT_TIMESTAMP);
