-- Source: Email list for invoice only.xlsx
-- Table: ITPROD.SHCUMAILD
-- Rule: Customer-specific rows keep TO only. Common CC for every invoice is stored once with CUSTOMER_CODE = 'ALL'.
-- Total rows: 54

INSERT INTO ITPROD.SHCUMAILD (CUSTOMER_CODE, RECIPIENT_TYPE, EMAIL_SEQ, EMAIL_ADDRESS, ACTIVE_STATUS) VALUES ('ALL', 'CC', 1, 'thitipong@patayafood.com', 'Y');
INSERT INTO ITPROD.SHCUMAILD (CUSTOMER_CODE, RECIPIENT_TYPE, EMAIL_SEQ, EMAIL_ADDRESS, ACTIVE_STATUS) VALUES ('ALL', 'CC', 2, 'thunyathorn@patayafood.com', 'Y');
INSERT INTO ITPROD.SHCUMAILD (CUSTOMER_CODE, RECIPIENT_TYPE, EMAIL_SEQ, EMAIL_ADDRESS, ACTIVE_STATUS) VALUES ('ALL', 'CC', 3, 'warissara@patayafood.com', 'Y');

INSERT INTO ITPROD.SHCUMAILD (CUSTOMER_CODE, RECIPIENT_TYPE, EMAIL_SEQ, EMAIL_ADDRESS, ACTIVE_STATUS) VALUES ('ETH0121', 'TO', 1, 'ronnachai.phattarapitarn@effem.com', 'Y');
INSERT INTO ITPROD.SHCUMAILD (CUSTOMER_CODE, RECIPIENT_TYPE, EMAIL_SEQ, EMAIL_ADDRESS, ACTIVE_STATUS) VALUES ('ETH0121', 'TO', 2, 'cherylsc.tan@effem.com', 'Y');
INSERT INTO ITPROD.SHCUMAILD (CUSTOMER_CODE, RECIPIENT_TYPE, EMAIL_SEQ, EMAIL_ADDRESS, ACTIVE_STATUS) VALUES ('ETH0121', 'TO', 3, 'mei-peng.lim@effem.com', 'Y');
INSERT INTO ITPROD.SHCUMAILD (CUSTOMER_CODE, RECIPIENT_TYPE, EMAIL_SEQ, EMAIL_ADDRESS, ACTIVE_STATUS) VALUES ('ETH0121', 'TO', 4, 'sophida.siriananchai@effem.com', 'Y');
INSERT INTO ITPROD.SHCUMAILD (CUSTOMER_CODE, RECIPIENT_TYPE, EMAIL_SEQ, EMAIL_ADDRESS, ACTIVE_STATUS) VALUES ('ETH0121', 'TO', 5, 'yingjian.tan@effem.com', 'Y');
INSERT INTO ITPROD.SHCUMAILD (CUSTOMER_CODE, RECIPIENT_TYPE, EMAIL_SEQ, EMAIL_ADDRESS, ACTIVE_STATUS) VALUES ('ETH0121', 'TO', 6, 'oscar.fong.1@effem.com', 'Y');
INSERT INTO ITPROD.SHCUMAILD (CUSTOMER_CODE, RECIPIENT_TYPE, EMAIL_SEQ, EMAIL_ADDRESS, ACTIVE_STATUS) VALUES ('ETH0121', 'TO', 7, 'huiyuan.teo.1@effem.com', 'Y');
INSERT INTO ITPROD.SHCUMAILD (CUSTOMER_CODE, RECIPIENT_TYPE, EMAIL_SEQ, EMAIL_ADDRESS, ACTIVE_STATUS) VALUES ('ETH0121', 'TO', 8, 'ryan.lee.1@effem.com', 'Y');
INSERT INTO ITPROD.SHCUMAILD (CUSTOMER_CODE, RECIPIENT_TYPE, EMAIL_SEQ, EMAIL_ADDRESS, ACTIVE_STATUS) VALUES ('ETH0121', 'TO', 9, 'arisa.sopitsakulvong@effem.com', 'Y');
INSERT INTO ITPROD.SHCUMAILD (CUSTOMER_CODE, RECIPIENT_TYPE, EMAIL_SEQ, EMAIL_ADDRESS, ACTIVE_STATUS) VALUES ('ETH0121', 'TO', 10, 'thanaporn.kusomrosananan@effem.com', 'Y');
INSERT INTO ITPROD.SHCUMAILD (CUSTOMER_CODE, RECIPIENT_TYPE, EMAIL_SEQ, EMAIL_ADDRESS, ACTIVE_STATUS) VALUES ('ETH0121', 'TO', 11, 'MARS.APINVOICE.MALAYSIA@EFFEM.COM', 'Y');
INSERT INTO ITPROD.SHCUMAILD (CUSTOMER_CODE, RECIPIENT_TYPE, EMAIL_SEQ, EMAIL_ADDRESS, ACTIVE_STATUS) VALUES ('ETH0122', 'TO', 1, 'ronnachai.phattarapitarn@effem.com', 'Y');
INSERT INTO ITPROD.SHCUMAILD (CUSTOMER_CODE, RECIPIENT_TYPE, EMAIL_SEQ, EMAIL_ADDRESS, ACTIVE_STATUS) VALUES ('ETH0122', 'TO', 2, 'arisa.sopitsakulvong@effem.com', 'Y');
INSERT INTO ITPROD.SHCUMAILD (CUSTOMER_CODE, RECIPIENT_TYPE, EMAIL_SEQ, EMAIL_ADDRESS, ACTIVE_STATUS) VALUES ('ETH0122', 'TO', 3, 'vincechester.gonzales@effem.com', 'Y');
INSERT INTO ITPROD.SHCUMAILD (CUSTOMER_CODE, RECIPIENT_TYPE, EMAIL_SEQ, EMAIL_ADDRESS, ACTIVE_STATUS) VALUES ('ETH0122', 'TO', 4, 'sophida.siriananchai@effem.com', 'Y');
INSERT INTO ITPROD.SHCUMAILD (CUSTOMER_CODE, RECIPIENT_TYPE, EMAIL_SEQ, EMAIL_ADDRESS, ACTIVE_STATUS) VALUES ('ETH0122', 'TO', 5, 'wyndell.diaz@effem.com', 'Y');
INSERT INTO ITPROD.SHCUMAILD (CUSTOMER_CODE, RECIPIENT_TYPE, EMAIL_SEQ, EMAIL_ADDRESS, ACTIVE_STATUS) VALUES ('ETH0122', 'TO', 6, 'dezaeuressa.b.bernabe@effem.com', 'Y');
INSERT INTO ITPROD.SHCUMAILD (CUSTOMER_CODE, RECIPIENT_TYPE, EMAIL_SEQ, EMAIL_ADDRESS, ACTIVE_STATUS) VALUES ('ETH0122', 'TO', 7, 'gichelle.gonzales@effem.com', 'Y');
INSERT INTO ITPROD.SHCUMAILD (CUSTOMER_CODE, RECIPIENT_TYPE, EMAIL_SEQ, EMAIL_ADDRESS, ACTIVE_STATUS) VALUES ('ETH0122', 'TO', 8, 'thanaporn.kusomrosananan@effem.com', 'Y');
INSERT INTO ITPROD.SHCUMAILD (CUSTOMER_CODE, RECIPIENT_TYPE, EMAIL_SEQ, EMAIL_ADDRESS, ACTIVE_STATUS) VALUES ('ETH0122', 'TO', 9, 'MARS.APINVOICE.PHILIPPINES@EFFEM.COM', 'Y');
INSERT INTO ITPROD.SHCUMAILD (CUSTOMER_CODE, RECIPIENT_TYPE, EMAIL_SEQ, EMAIL_ADDRESS, ACTIVE_STATUS) VALUES ('ETH0362', 'TO', 1, 'ronnachai.phattarapitarn@effem.com', 'Y');
INSERT INTO ITPROD.SHCUMAILD (CUSTOMER_CODE, RECIPIENT_TYPE, EMAIL_SEQ, EMAIL_ADDRESS, ACTIVE_STATUS) VALUES ('ETH0362', 'TO', 2, 'Jak_Mkt_PETCARE_AP@effem.com', 'Y');
INSERT INTO ITPROD.SHCUMAILD (CUSTOMER_CODE, RECIPIENT_TYPE, EMAIL_SEQ, EMAIL_ADDRESS, ACTIVE_STATUS) VALUES ('ETH0362', 'TO', 3, 'pindo.anggoro@effem.com', 'Y');
INSERT INTO ITPROD.SHCUMAILD (CUSTOMER_CODE, RECIPIENT_TYPE, EMAIL_SEQ, EMAIL_ADDRESS, ACTIVE_STATUS) VALUES ('ETH0362', 'TO', 4, 'agustinus.tobing@effem.com', 'Y');
INSERT INTO ITPROD.SHCUMAILD (CUSTOMER_CODE, RECIPIENT_TYPE, EMAIL_SEQ, EMAIL_ADDRESS, ACTIVE_STATUS) VALUES ('ETH0362', 'TO', 5, 'sophida.siriananchai@effem.com', 'Y');
INSERT INTO ITPROD.SHCUMAILD (CUSTOMER_CODE, RECIPIENT_TYPE, EMAIL_SEQ, EMAIL_ADDRESS, ACTIVE_STATUS) VALUES ('ETH0362', 'TO', 6, 'arisa.sopitsakulvong@effem.com', 'Y');
INSERT INTO ITPROD.SHCUMAILD (CUSTOMER_CODE, RECIPIENT_TYPE, EMAIL_SEQ, EMAIL_ADDRESS, ACTIVE_STATUS) VALUES ('ETH0362', 'TO', 7, 'thanaporn.kusomrosananan@effem.com', 'Y');
INSERT INTO ITPROD.SHCUMAILD (CUSTOMER_CODE, RECIPIENT_TYPE, EMAIL_SEQ, EMAIL_ADDRESS, ACTIVE_STATUS) VALUES ('ETH0362', 'TO', 8, 'MARS.APINVOICE.INDONESIA@EFFEM.COM', 'Y');
INSERT INTO ITPROD.SHCUMAILD (CUSTOMER_CODE, RECIPIENT_TYPE, EMAIL_SEQ, EMAIL_ADDRESS, ACTIVE_STATUS) VALUES ('ETH0087', 'TO', 1, 'MARS.APINVOICOE.IND@effem.com', 'Y');
INSERT INTO ITPROD.SHCUMAILD (CUSTOMER_CODE, RECIPIENT_TYPE, EMAIL_SEQ, EMAIL_ADDRESS, ACTIVE_STATUS) VALUES ('ETH0087', 'TO', 2, 'venu.venna@effem.com', 'Y');
INSERT INTO ITPROD.SHCUMAILD (CUSTOMER_CODE, RECIPIENT_TYPE, EMAIL_SEQ, EMAIL_ADDRESS, ACTIVE_STATUS) VALUES ('ETH0087', 'TO', 3, 'bharat.bagusetty@effem.com', 'Y');
INSERT INTO ITPROD.SHCUMAILD (CUSTOMER_CODE, RECIPIENT_TYPE, EMAIL_SEQ, EMAIL_ADDRESS, ACTIVE_STATUS) VALUES ('ETH0087', 'TO', 4, 'sankardass.k@effem.com', 'Y');
INSERT INTO ITPROD.SHCUMAILD (CUSTOMER_CODE, RECIPIENT_TYPE, EMAIL_SEQ, EMAIL_ADDRESS, ACTIVE_STATUS) VALUES ('ETH0087', 'TO', 5, 'pegallapati.sai-kiran@effem.com', 'Y');
INSERT INTO ITPROD.SHCUMAILD (CUSTOMER_CODE, RECIPIENT_TYPE, EMAIL_SEQ, EMAIL_ADDRESS, ACTIVE_STATUS) VALUES ('ETH0087', 'TO', 6, 'arisa.sopitsakulvong@effem.com', 'Y');
INSERT INTO ITPROD.SHCUMAILD (CUSTOMER_CODE, RECIPIENT_TYPE, EMAIL_SEQ, EMAIL_ADDRESS, ACTIVE_STATUS) VALUES ('ETH0087', 'TO', 7, 'thanaporn.kusomrosananan@effem.com', 'Y');
INSERT INTO ITPROD.SHCUMAILD (CUSTOMER_CODE, RECIPIENT_TYPE, EMAIL_SEQ, EMAIL_ADDRESS, ACTIVE_STATUS) VALUES ('ETH0319', 'TO', 1, 'marsanz.ap@acp.effem.com', 'Y');
INSERT INTO ITPROD.SHCUMAILD (CUSTOMER_CODE, RECIPIENT_TYPE, EMAIL_SEQ, EMAIL_ADDRESS, ACTIVE_STATUS) VALUES ('ETH0319', 'TO', 2, 'importsau@effem.com', 'Y');
INSERT INTO ITPROD.SHCUMAILD (CUSTOMER_CODE, RECIPIENT_TYPE, EMAIL_SEQ, EMAIL_ADDRESS, ACTIVE_STATUS) VALUES ('ETH0319', 'TO', 3, 'arisa.sopitsakulvong@effem.com', 'Y');
INSERT INTO ITPROD.SHCUMAILD (CUSTOMER_CODE, RECIPIENT_TYPE, EMAIL_SEQ, EMAIL_ADDRESS, ACTIVE_STATUS) VALUES ('ETH0319', 'TO', 4, 'thanaporn.kusomrosananan@effem.com', 'Y');
INSERT INTO ITPROD.SHCUMAILD (CUSTOMER_CODE, RECIPIENT_TYPE, EMAIL_SEQ, EMAIL_ADDRESS, ACTIVE_STATUS) VALUES ('ETH0149', 'TO', 1, 'marsanz.ap@acp.effem.com', 'Y');
INSERT INTO ITPROD.SHCUMAILD (CUSTOMER_CODE, RECIPIENT_TYPE, EMAIL_SEQ, EMAIL_ADDRESS, ACTIVE_STATUS) VALUES ('ETH0149', 'TO', 2, 'arisa.sopitsakulvong@effem.com', 'Y');
INSERT INTO ITPROD.SHCUMAILD (CUSTOMER_CODE, RECIPIENT_TYPE, EMAIL_SEQ, EMAIL_ADDRESS, ACTIVE_STATUS) VALUES ('ETH0149', 'TO', 3, 'thanaporn.kusomrosananan@effem.com', 'Y');
INSERT INTO ITPROD.SHCUMAILD (CUSTOMER_CODE, RECIPIENT_TYPE, EMAIL_SEQ, EMAIL_ADDRESS, ACTIVE_STATUS) VALUES ('ETH0149', 'TO', 4, 'luke.poelman@effem.com', 'Y');
INSERT INTO ITPROD.SHCUMAILD (CUSTOMER_CODE, RECIPIENT_TYPE, EMAIL_SEQ, EMAIL_ADDRESS, ACTIVE_STATUS) VALUES ('ETH0052', 'TO', 1, 'dennis.thomas@gac.com', 'Y');
INSERT INTO ITPROD.SHCUMAILD (CUSTOMER_CODE, RECIPIENT_TYPE, EMAIL_SEQ, EMAIL_ADDRESS, ACTIVE_STATUS) VALUES ('ETH0052', 'TO', 2, 'exd.payable@effem.com', 'Y');
INSERT INTO ITPROD.SHCUMAILD (CUSTOMER_CODE, RECIPIENT_TYPE, EMAIL_SEQ, EMAIL_ADDRESS, ACTIVE_STATUS) VALUES ('ETH0052', 'TO', 3, 'admin-mars.dubai@gac.com', 'Y');
INSERT INTO ITPROD.SHCUMAILD (CUSTOMER_CODE, RECIPIENT_TYPE, EMAIL_SEQ, EMAIL_ADDRESS, ACTIVE_STATUS) VALUES ('ETH0052', 'TO', 4, 'Subi.Akbar@effem.com', 'Y');
INSERT INTO ITPROD.SHCUMAILD (CUSTOMER_CODE, RECIPIENT_TYPE, EMAIL_SEQ, EMAIL_ADDRESS, ACTIVE_STATUS) VALUES ('ETH0052', 'TO', 5, 'sherif.tarek@effem.com', 'Y');
INSERT INTO ITPROD.SHCUMAILD (CUSTOMER_CODE, RECIPIENT_TYPE, EMAIL_SEQ, EMAIL_ADDRESS, ACTIVE_STATUS) VALUES ('ETH0052', 'TO', 6, 'arisa.sopitsakulvong@effem.com', 'Y');
INSERT INTO ITPROD.SHCUMAILD (CUSTOMER_CODE, RECIPIENT_TYPE, EMAIL_SEQ, EMAIL_ADDRESS, ACTIVE_STATUS) VALUES ('ETH0052', 'TO', 7, 'thanaporn.kusomrosananan@effem.com', 'Y');
INSERT INTO ITPROD.SHCUMAILD (CUSTOMER_CODE, RECIPIENT_TYPE, EMAIL_SEQ, EMAIL_ADDRESS, ACTIVE_STATUS) VALUES ('ETH0052', 'TO', 8, 'MARS.APINVOICE.UNITEDARABEMIRATES@EFFEM.COM', 'Y');
