-- SHDOCPERM -   permission workflow
-- Run manually on DB2 AS400 after backup/review.

CREATE TABLE ITPROD.SHDOCPERM (
    PERSON_CODE    CHAR(20)      NOT NULL,
    PAGE_CODE      VARCHAR(50)   NOT NULL,
    PERMISSION_GROUP VARCHAR(20)  NOT NULL DEFAULT '',
    ACTIVE_STATUS  CHAR(1)       NOT NULL DEFAULT 'Y',
    CREATED_DATE   TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE   TIMESTAMP,
    UPDATED_USER   CHAR(20)      NOT NULL DEFAULT '',

    CONSTRAINT PK_SHDOCPERM PRIMARY KEY (PERSON_CODE, PAGE_CODE),
    CONSTRAINT CK_SHDOCPERM_STATUS CHECK (ACTIVE_STATUS IN ('Y', 'N'))
);

INSERT INTO ITPROD.SHDOCPERM
    (PERSON_CODE, PAGE_CODE, PERMISSION_GROUP, ACTIVE_STATUS, CREATED_DATE, UPDATED_DATE, UPDATED_USER)
VALUES
    ('16710231', 'PERMISSION_ADMIN', 'ADMIN', 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM');

-- Existing table migration:
-- ALTER TABLE ITPROD.SHDOCPERM ADD COLUMN PERMISSION_GROUP VARCHAR(20) NOT NULL DEFAULT '';

-- Supported PAGE_CODE values:
-- CUSTOMER_EMAIL
-- ADMIN_EMAIL
-- ADMIN_EMAIL_TEMPLATE
-- ADMIN_EMAIL_SENDER
-- ADMIN_EMAIL_LOG
-- PROGRAM_UPDATE_ADMIN
-- PERMISSION_ADMIN

INSERT INTO ITPROD.SHDOCPERM
    (PERSON_CODE, PAGE_CODE, PERMISSION_GROUP, ACTIVE_STATUS, CREATED_DATE, UPDATED_DATE, UPDATED_USER)
SELECT '16710231', 'PROGRAM_UPDATE_ADMIN', 'ADMIN', 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM'
  FROM SYSIBM.SYSDUMMY1
 WHERE NOT EXISTS (
       SELECT 1
         FROM ITPROD.SHDOCPERM
        WHERE PERSON_CODE = '16710231'
          AND PAGE_CODE = 'PROGRAM_UPDATE_ADMIN'
   );

-- Existing ADMIN groups migration:
INSERT INTO ITPROD.SHDOCPERM
    (PERSON_CODE, PAGE_CODE, PERMISSION_GROUP, ACTIVE_STATUS, CREATED_DATE, UPDATED_DATE, UPDATED_USER)
SELECT DISTINCT PERSON_CODE, 'ADMIN_EMAIL_LOG', PERMISSION_GROUP, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM'
  FROM ITPROD.SHDOCPERM p
 WHERE PERMISSION_GROUP = 'ADMIN'
   AND NOT EXISTS (
       SELECT 1
         FROM ITPROD.SHDOCPERM e
        WHERE e.PERSON_CODE = p.PERSON_CODE
          AND e.PAGE_CODE = 'ADMIN_EMAIL_LOG'
   );

INSERT INTO ITPROD.SHDOCPERM
    (PERSON_CODE, PAGE_CODE, PERMISSION_GROUP, ACTIVE_STATUS, CREATED_DATE, UPDATED_DATE, UPDATED_USER)
SELECT DISTINCT PERSON_CODE, 'PROGRAM_UPDATE_ADMIN', PERMISSION_GROUP, 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM'
  FROM ITPROD.SHDOCPERM p
 WHERE PERMISSION_GROUP = 'ADMIN'
   AND NOT EXISTS (
       SELECT 1
         FROM ITPROD.SHDOCPERM e
        WHERE e.PERSON_CODE = p.PERSON_CODE
          AND e.PAGE_CODE = 'PROGRAM_UPDATE_ADMIN'
   );
