-- SHDOCPERM -   permission workflow
-- Run manually on DB2 AS400 after backup/review.

CREATE TABLE ITPROD.SHDOCPERM (
    PERSON_CODE    CHAR(20)      NOT NULL,
    PAGE_CODE      VARCHAR(50)   NOT NULL,
    PERMISSION_GROUP VARCHAR(20)  NOT NULL DEFAULT '',
    ACTIVE_STATUS  CHAR(1)       NOT NULL DEFAULT 'Y',
    CREATED_DATE   TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE   TIMESTAMP,
    UPDATED_USER   CHAR(20)      NOT NULL DEFAULT '',

    CONSTRAINT PK_SHDOCPERM PRIMARY KEY (PERSON_CODE, PAGE_CODE),
    CONSTRAINT CK_SHDOCPERM_STATUS CHECK (ACTIVE_STATUS IN ('Y', 'N'))
);

INSERT INTO ITPROD.SHDOCPERM
    (PERSON_CODE, PAGE_CODE, PERMISSION_GROUP, ACTIVE_STATUS, CREATED_DATE, UPDATED_DATE, UPDATED_USER)
VALUES
    ('16710231', 'PERMISSION_ADMIN', 'ADMIN', 'Y', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SYSTEM');

-- Existing table migration:
-- ALTER TABLE ITPROD.SHDOCPERM ADD COLUMN PERMISSION_GROUP VARCHAR(20) NOT NULL DEFAULT '';

-- Supported PAGE_CODE values:
-- CUSTOMER_EMAIL
-- ADMIN_EMAIL
-- ADMIN_EMAIL_TEMPLATE
-- ADMIN_EMAIL_SENDER
-- PERMISSION_ADMIN
